spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sustc  # change this to your own jdbc url
    username: sustc  # change this to your own username (avoid using a superuser)
    password: sustc  # change this to your own password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

logging:
  level:
    root: off
    io.sustc: debug

---

benchmark:
  data-path: data
  student-mode: true
